<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="itext7" Version="8.0.5" />
		<PackageReference Include="itext7.bouncy-castle-adapter" Version="8.0.5" />
	</ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\TPS.Infrastructure\TPS.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\StudentArea\Events\Commands\" />
    <Folder Include="Areas\StudentArea\Events\Contracts\" />
    <Folder Include="Areas\StudentArea\Societies\Contracts\" />
    <Folder Include="Areas\StudentArea\Societies\Commands\" />
    <Folder Include="Areas\StudentArea\Students\Queries\" />
  </ItemGroup>

</Project>
