<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UserSecretsId>e227a502-e3c4-48bf-b3c0-1a176db33abb</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Data\Migrations\**" />
	  <EmbeddedResource Remove="Data\Migrations\**" />
	  <None Remove="Data\Migrations\**" />
	</ItemGroup>



	<ItemGroup>
		<PackageReference Include="Bogus" Version="35.6.3" />
		<PackageReference Include="MicroElements.Swashbuckle.FluentValidation" Version="6.1.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Quartz" Version="3.14.0" />
		<PackageReference Include="Microsoft.Extensions.AI" Version="9.4.0-preview.1.25207.5" />
		<PackageReference Include="Microsoft.Extensions.AI.Ollama" Version="9.4.0-preview.1.25207.5" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TSP.Domain\TSP.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Migrations\" />
	</ItemGroup>

</Project>
